### PR TITLE
Version 1.3

### PR DESCRIPTION
**Pull request by sepandhaghighi**
#### Reference Issues/PRs
#144 #145 #146 #147
#### What does this implement/fix? Explain your changes.
Version 1.3

### CODE REVIEW

**Comment by sepandhaghighi** [comment]
@sadrasabouri @sarminh @kasraaskari  Hi folks
Please complete this review until **Wednesday - 2021-06-30 - 11:59 AM GMT+3:30**
**Notice:** Only review, don't need to merge

**Review by sarminh — COMMENTED** [review]
Cool.

**Review by sarminh — APPROVED** [review]

**Review by sadrasabouri — APPROVED** [review]
Nice.
🆗 PR
🆗 Jupyter Notebook
🤔 .exe file (Not tested)

**Review by kasraaskari — APPROVED** [review]
@sepandhaghighi Thanks a lot.

**Pull request merged**
